### ISSUE TITLE
Sometimes fail to parse gl headers

### ISSUE THREAD

**Issue by Constellation** [intel/fastuidraw#16]
I occasionally encounter the error, that fail to emit `sm_CallUnloadableFuntion` to the result.
I guess this is due to the static member variables referenced in the header (HeaderCreator.hpp).

**Comment by krogueintel** [comment]
Can you paste the error message here. Does this error message only show up during building? (It should be at most only at build)

**Comment by krogueintel** [comment]
I've just made a commit where static member variables of openGL_function_info are removed and replaced by members of an object which is instanced once where that instance is accessed from a function. Let me know if there are any (occasional) errors for generating the NGL stuff.

**Comment by krogueintel** [comment]
Have you seen the error at all since the commit mentioned in the previous comment? If not, I can close the issue.

**Comment by krogueintel** [comment]
I guess this can be closed from that no comments in a year and I have not seen the issue myself.
