### ISSUE TITLE
it works also on a CPU

### ISSUE THREAD

**Issue by ghost** [intel/fastuidraw#19]
Hi,

It's not a bug, just an info.
I've tried to use fastuidraw with intel software rasterizer (SWR / Mesa 17.0.5), and it works.
It works well enough to run the benchmark, but it probably needs more tests to see if swr could be used as a fallback.

Tested on a i3 4160, with remote acces via X2Go (so, probably the worst configuration), with a 1280x1280 screen resolution : 
Cairo : 32.7 FPS
FastUI+swr : 1.9 FPS

swr use 2 CPU cores and Cairo one CPU core.

**Comment by krogueintel** [comment]
Hi,

 I have to admit that I think that using FastUIDraw on a platform without a GPU is to use it terribly incorrectly. The GPU API's (OpenGL, Vulkan, Metal, D3D for example) are the way they are to reflect the kind of loads and how to process those loads a GPU is to do. FastUIDraw's purpose is to make optimal use of a GPU through such an API in such a way that avoids usage patterns that harm GPU performance (state thrashing and that a GPU draws triangles being the primary ones) and to take advantage of the fixed functionality of a typical GPU (samplers and parallelixation of fragment processing). Using a FastUIDraw on a CPU implementation of a graphics API is never going to be performant and I strongly advise against it.

Why would one use FastUIDraw on a platform that does not have a GPU?

**Comment by ghost** [comment]
Hi,

I absolutely agree with you, don't have any doubt about that :-)
and by no way, i meant to says it could be used as a cpu-only API, sorry if i've been unclear.

There are just some cases, like remote access for example, where you can't use a GPU (well, mostly).
It is why i have say "fallback" ;-)
