### ISSUE TITLE
Missing include?

### ISSUE THREAD

**Issue by bgroff** [intel/fastuidraw#36]
On macOS `<algorithm>` needs to be included for std::fill. 

https://github.com/intel/fastuidraw/blob/ccce055556446f8afdb20fa9ca1f2dcc8d9dbcd9/src/fastuidraw/text/glyph.cpp#L92

These two lines break the build for mac.

**Comment by krogueintel** [comment]
Thank you for the report; the fix you suggested has been pushed.

Please let me know how far you get along with FastUIDraw on Mac, as attempts before have been hard (most of the pain in the building of the GL backend).
