### ISSUE TITLE
benchmarks source codes

### ISSUE THREAD

**Issue by xlazom00** [intel/fastuidraw#4]
Hello 
sorry this isn't issue but
can you share source code of your benchmars that you use in your XDC2016 presentation
As I would like to see why Qt scenegraph is slower then fast ui draw
Thx

**Comment by FabriceSalvaire** [comment]
**I missed in the benchmarked Qt application code using modern Qt5 Scene Graph API.**

**Which API are you comparing to what?**

**IMHO It doesn't make sense to  benchmark the old Qt4 Painter.**

Slide 4 is meaningless until we don't known which API is used!

**Comment by krogueintel** [comment]
Hi,

 Qt Scene Graph does not really offer a "native" canvas API. The best you can have is an interface that maps to QPainter, take a look at http://doc.qt.io/qt-5/qquickpainteditem.html. Depending on things, one can can get the raster or GL backend with the painter. For content within that element that changes every frame, there is a cost of either blitting to texture then drawing the texture (using QImage) or just drawing the texture if have the GL backend. 

 FastUIDraw is for implementing (quickly) an imperative 2D drawing API. I think those that are wondering why Qt Scene Graph and QML are not present in the benchmarks, need to first understand the purpose of FastUIDraw: to implement a traditional imperative 2D renderer using the GPU. Qt Scene Graph does NOT do that, and it makes no claim to attempt to do so.

**Comment by xlazom00** [comment]
Qt Scene Graph don't have this api but you can use QML
as all primitives that you use in your benchmark are there
It is same as you do from HTML

**Comment by krogueintel** [comment]
Given that the code is open, I am happy to accept pull requests for a painter-cells port to QML2 which has all the features that the current port to Qpainter port has. 

I think those that walk the road to make such a port to QML will have significant amount of work to do. 

However, this discussion utterly misses the entire point of what FastUIDraw aims to provide: a high performance implementation of imperative canvas rendering. This is NOT what QML aims to do at all.

**Comment by FabriceSalvaire** [comment]
Yes you are right the Qt5 QML Canvas item actually uses the old Qt4 Painter. I guess it is not a high priority at Qt company to work on this (W3C canvas on GPU).

If I understand well, you are working on something similar to NVidia NV Path API  (which seems to be a dead project ???).

But your benchmark described in slide 2 (as said by xlazom00) is implementable on top of the Qt5 Scene Graph. Thus you should compare to it or write explicitly in your slide you are using the Qt4 Painter which is known to be flawed. Qt guys did a lot of benchmarks on low cost platform to design the new painter engine.

Additionally, we can test 2D rendering using QML as I did in 
https://github.com/FabriceSalvaire/qt5-vector-graphic-shaders
It runs nearly on all platforms and it isn't so easy to achieve a good rendering in all cases.

**Comment by krogueintel** [comment]
I make it pretty explicit that the port is Qpainter and not QML in the talk. 

The only canvas interface Qt has is Qpainter with different backends:native, raster and GL. This is the interface to which to compare. There is little, if any , difference between the Qpaiinter in qt4.7 and qt5.x. The fundamental issue with Qpainter is that it was born first with CPU rendering only. 

At any rate, I will close this discussion now because it appears everyone now understands why the comparison is against Qpainter and that QML seeks to solve a different problem.

**Comment by krogueintel** [comment]
One more comment on the NVIDIA front: NVIDIA had a GL extension to render paths; that extension is not in any way a complete solution to canvas rendering .. It can be used to help though. 

FastUIDraw aims to be a solution for canvas rendering with high performance even with complicated loads; the main difference between FastUIDraw and others is that it requires a GPU and scales much better than others currently.
