### ISSUE TITLE
Prefix NGL exe with ./ on Linux in Makefile

### ISSUE THREAD

**Issue by likewise** [intel/fastuidraw#43]
I had to prefix the executables with ./ on Linux in order to have this work.

`diff --git a/src/fastuidraw/gl_backend/ngl_generator/Rules.mk b/src/fastuidraw/gl_backend/ngl_generator/Rules.mk
index c9439cb..455942f 100644
--- a/src/fastuidraw/gl_backend/ngl_generator/Rules.mk
+++ b/src/fastuidraw/gl_backend/ngl_generator/Rules.mk
@@ -6,8 +6,8 @@ d               := $(dir)
 
 NGL_DIRECTORY := $(d)
 NGL_BUILD := build/ngl_generator
-NGL_FILTER := $(NGL_BUILD)/filter
-NGL_EXTRACTOR := $(NGL_BUILD)/extractor
+NGL_FILTER := ./$(NGL_BUILD)/filter
+NGL_EXTRACTOR := ./$(NGL_BUILD)/extractor`

**Comment by krogueintel** [comment]
Can you share what distro or environment? Linux is the primary target and on the distros I have tested (admittedly mostly debian based), the ./ has not been necessary.

**Comment by likewise** [comment]
This was with a Yocto under Linux Mint (Ubuntu 16.04) based. But the issue has disappeared altogether while I was cooking up proper Yocto support, so I must have hit something else.
