### ISSUE TITLE
make check: SDL2 image error unclear.

### ISSUE THREAD

**Issue by arskama** [intel/fastuidraw#44]
Output of make check:

(base) amandy@poppolop:~/Repos/WebTeam_2019/fastuidraw$ make check
Package SDL2_image was not found in the pkg-config search path.
Perhaps you should add the directory containing `SDL2_image.pc'
to the PKG_CONFIG_PATH environment variable
No package 'SDL2_image' found
/bin/sh: 1: Syntax error: end of file unexpected
/bin/sh: 1: Syntax error: end of file unexpected
Cannot build demos: Unable to find SDL2_image cflags from pkg-config SDL2_image: 
Cannot build demos: Unable to find SDL2_image libs from pkg-config SDL2_image: 
----------------------------------------------------------
Since I have no idea what this is, I have no idea where to get it or install that.

**Comment by arskama** [comment]
ok, I was able to install it with:
apt-get install libsdl2-image-dev

 No more issue, but maybe packages to install (names or even commands for dummies) should be explicit.

**Comment by krogueintel** [comment]
I've added text to the effect "Install package with SDL2_image development files, for example on Ubuntu, apt install libsdl2-image-dev".

**Comment by krogueintel** [comment]
If this is sufficient let me know and I will close the issue

**Comment by arskama** [comment]
GTM. can close
thanks
