### ISSUE TITLE
Could not set the background color

### ISSUE THREAD

**Issue by leonsal** [intel/fastuidraw#48]
Hi,

In my tests after generating the drawing commands for several rectangles, 
the framebuffer is cleared to white, but the background of my window remains black.
Please see the [screenshot](https://github.com/leonsal/fastuidraw_tests/blob/master/fastuidraw.png).

Commands executed after drawing the rectangles:
```  
...
mPainter->end();
// Make sure we are rendering to the default fraembuffer of GL
fastuidraw_glBindFramebuffer(GL_DRAW_FRAMEBUFFER, 0);

// Clear the framebuffer
fastuidraw_glClearColor(1.0, 1.0, 1.0, 1.0);
fastuidraw_glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

// blit the contents of m_surface to the default framebuffer with nearest filtering
mSurface->blit_surface(GL_NEAREST);
...
```
Any ideas of what could be wrong ?

**Comment by krogueintel** [comment]
The function blit_surface() copies the contents of the surface to the framebuffer which completely overwrites the contents of the framebuffer; you need to give the PainterSurfaceGL object the white background. This is done by the method clear_color() of PainterSurface: https://intel.github.io/fastuidraw/docs/html/d5/d60/classfastuidraw_1_1_painter_surface.html#a7faefd57636f4c98b13ed6aab6744cab .

**Comment by leonsal** [comment]
It worked, but when I continuously resize the window, the background color alternates between
black and white in a flickering effect. Please see [this](https://github.com/leonsal/fastuidraw_tests/blob/master/flicker.gif).

**Comment by krogueintel** [comment]
You need to set the clear color before Painter::begin(). That function clears the surface with it's clear color.

**Comment by krogueintel** [comment]
If setting he clear color resolved the issue, we should close it.

**Comment by leonsal** [comment]
It is much better, though there are still some artifacts. I will continue testing. Thanks.
