### ISSUE TITLE
Wrong link on https://www.x.org/wiki/Events/XDC2016/Program/rogovin_fast_ui_draw/

### ISSUE THREAD

**Issue by janisozaur** [intel/fastuidraw#6]
Hi, sorry for reporting it here, I'm not sure where else would be better.

I noticed link to video on https://www.x.org/wiki/Events/XDC2016/Program/rogovin_fast_ui_draw/ is wrong. It points to day 1 stream, while it should point to day 2 stream (https://www.youtube.com/watch?v=2ryvYS47V0E)

**Comment by krogueintel** [comment]
I sent a message to the X.org people and they have fixed the link. 

Thankyou very much for reporting the issue.
