### ISSUE TITLE
C++11 upgrade

### ISSUE THREAD

**Issue by Constellation** [intel/fastuidraw#7]
I saw the [post in webkit-dev](https://lists.webkit.org/pipermail/webkit-dev/2016-November/028530.html) and started looking fastuidraw. That's super awesome!

Looking through the code, the use of the boost library is fairly limited.
If we can enable C++11, I think we can replace the part of them with the std's ones.
For example, threading primitives can be replaced.

What do you think of  using C++11 in the fastuidraw code base?

**Comment by krogueintel** [comment]
I am not particular about it, except that I want to make sure that the project continues to build under Msys2 (and hopefully MinGW/Msys as well).

I made a very recent commit to remove using boost::checked_delete, and the remaining uses of boost are:
 - Providing a mutex class
 - Providing an atomic int class
 - multi-dimensional array stuff
 - Stuff for freetype_util

The first two have obvious C++11 of even C-something versions. Not too sure about the third, but it is not a big deal to roll my own for the few uses I have. The main pain is the stuff in freetype_util which I want to rewrite (and in truth have wanted to rewrite for a LONG time).

I plan to phase out using boost. I am really happy to accept merge requests phasing out the boost stuff as well.

**Comment by Constellation** [comment]
I think msys2's GCC is new enough to enable C++11 support in some areas.
According to MSYS2's package info, the version of GCC is 5.3.0 https://github.com/Alexpux/MSYS2-packages/blob/master/gcc/PKGBUILD
And in MinGW case, the version of GCC is 4.9.0 https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/PKGBUILD

In both cases, C++11 is already supported.

**Comment by krogueintel** [comment]
I've merged Contellation's pull requests and have committed more to also remove the need to link against boost libs.

However, there are two places that boost headers are still used in the building of the .so's:
  -freetype_util (which I desperately want to refactor or rewrite)
  -image.cpp is using boost/multi_array.hpp still

**Comment by krogueintel** [comment]
Thankyou Constellation for the patches removing more of boost from freetype_util.

**Comment by Constellation** [comment]
@krogueintel 

As a first step, I created the 2 PRs, one for multi_array and one for signals.
Since the both functionality is pretty simple, we can easily replace it with our own implementations.

**Comment by krogueintel** [comment]
I've merged your 2 PR's and a very satisfying grep result:

grep -ri boost .

yields nothing now, so we close this \o/

**Comment by Constellation** [comment]
Great!
